name: Terraform CI/CD

on:
  push:
    branches:
      - main
  
jobs:
    deploy-infrastructure:
        runs-on: ubuntu-24.04
   
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v6
              with: 
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-region: ${{secrets.AWS_REGION}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v4
              
            - name: Terraform init
              run: terraform -chdir=terraform init
            - name: Validate terraform
              run: terraform -chdir=terraform validate
            - name: Create terraform tfvars
              run: |
                cat << 'EOF' > terraform/terraform.tfvars
                  repo_url           = "${{ secrets.REPO_URL }}"
                  gh_pat             = "${{ secrets.GH_PAT }}"
                  MAIL_USERNAME      = "${{ secrets.MAIL_USERNAME }}"
                  MAIL_PASSWORD      = "${{ secrets.MAIL_PASSWORD }}"
                  MAIL_PORT          = "${{ secrets.MAIL_PORT }}"
                  MAIL_SERVER        = "${{ secrets.MAIL_SERVER }}"
                  MAIL_FROM_NAME     = "${{ secrets.MAIL_FROM_NAME }}"
                  MAIL_FROM          = "${{ secrets.MAIL_FROM }}"
                  AMADEUS_API_KEY    = "${{ secrets.AMADEUS_API_KEY }}"
                  AMADEUS_API_SECRET = "${{ secrets.AMADEUS_API_SECRET }}"
                  AMADEUS_BASE_URL   = "${{ secrets.AMADEUS_BASE_URL }}"
                  JWT_SECRET_KEY     = "${{ secrets.JWT_SECRET_KEY }}"
                  JWT_ALG            = "${{ secrets.JWT_ALG }}"
                EOF
            - name: Plan Terraform
              run: terraform -chdir=terraform plan -out=tfplan
            - name: Terraform Apply
              run: terraform -chdir=terraform apply -auto-approve tfplan
         
